name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - staging

jobs:
  tests:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec spec/htmlbook_spec.rb